CREATE TABLE User_Table
(
	[Id] INT NOT NULL PRIMARY KEY, 
	[Email] NVARCHAR(20) UNIQUE,
    [username] NVARCHAR(20) NOT NULL, 
    [password] VARCHAR(20) NOT NULL, 
    [level] INT NOT NULL
)
CREATE TABLE PRODUCE_ACT
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Title] NVARCHAR(50) NOT NULL,
	[Contains] NVARCHAR(MAX) NOT NULL,
	[Author] NVARCHAR(20),
	FOREIGN KEY(Author) REFERENCES USER_TABLE(email)
)
CREATE TABLE KNOWLEDGES
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Title] NVARCHAR(50) NOT NULL,
	[Contains] NVARCHAR(MAX) NOT NULL,
	[Author] NVARCHAR(20)
	FOREIGN KEY(Author) REFERENCES USER_TABLE(EMAIL)
)
CREATE TABLE BUSSINESS_BUY 
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name_Buss] NVARCHAR(20),
	[Name_seed] NVARCHAR(20),
	[Price_buy] NVARCHAR(10),
	[UpdateDay] DATE,
	[Author] NVARCHAR(20),
	FOREIGN KEY(Author) REFERENCES USER_TABLE(EMAIL)
)
CREATE TABLE COSTS
(
	[Id] INT NOT NULL PRIMARY KEY,
	[TenNongSan] NVARCHAR(20),
	[Giathitruong] NVARCHAR(10) NOT NULL,
	[UpdateDay] DATE,
	[Author] NVARCHAR(20),
	FOREIGN KEY (Author) REFERENCES USER_TABLE(EMAIL)
)
