INSERT INTO [dbo].[User_Table] ([Id], [Email], [username], [password], [level]) VALUES (1, N'huong@gmail.com', N'Huong', N'1234', 1)
INSERT INTO [dbo].[User_Table] ([Id], [Email], [username], [password], [level]) VALUES (2, N'nha@gmail.com', N'Nha', N'1234', 1)
INSERT INTO [dbo].[KNOWLEDGES] ([Id], [Title], [Contains], [Author]) VALUES (1, N'Kĩ thuật trồng lúa', N'~/Database/Knowlegde/1.txt', N'huong@gmail.com')
INSERT INTO [dbo].[KNOWLEDGES] ([Id], [Title], [Contains], [Author]) VALUES (2, N'Sumary The man and the sea', N'~/Database/Knowledge/2.txt', N'huong@gmail.com')
INSERT INTO [dbo].[KNOWLEDGES] ([Id], [Title], [Contains], [Author]) VALUES (3, N'test', N'~/Database/Knowledge/3.txt', N'nha@gmail.com')
