//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhuyenNong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BUSSINESS_BUY> BUSSINESS_BUY { get; set; }
        public virtual DbSet<COST> COSTS { get; set; }
        public virtual DbSet<KNOWLEDGE> KNOWLEDGES { get; set; }
        public virtual DbSet<PRODUCE_ACT> PRODUCE_ACT { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
    }
}
