CREATE TABLE [dbo].[ShowHome] (
    [Id]          INT            NOT NULL,
    [linkImage]   VARCHAR (100)  NULL,
    [Title]       NVARCHAR (100) NOT NULL,
    [Summary]     NVARCHAR (400) NULL,
    [dateWritten] DATETIME       NULL,
    [linkPage]    VARCHAR (100)  NOT NULL,
    [Type]        INT  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

INSERT INTO [dbo].[ShowHome] ([Id], [linkImage], [Title], [Summary], [dateWritten], [linkPage], [Type]) VALUES (1, N'/Assets/HomePage/images/kn1.jpg', N'Khoai lang xuất khẩu tăng giá', N'Hiện thương lái tìm mua khoai lang tím Nhật với giá 800.000 - 850.000 đồng/tạ (tính 60kg/tạ), tăng gấp nhiều lần so với thời điểm quý 2-2015 giá chỉ 100.000 - 150.000 đồng/tạ. Giá khoai tăng do nhu cầu xuất khẩu sang thị trường Trung Quốc đang hút hàng và vụ khoai ở ĐBSCL đang vào mùa nghịch nên sản lượng rất ít.', N'2015-11-28 16:00:00', N'/Detail/detail', 2)
INSERT INTO [dbo].[ShowHome] ([Id], [linkImage], [Title], [Summary], [dateWritten], [linkPage], [Type]) VALUES (2, N'/Assets/HomePage/images/kn2.jpg', N'Lượng giá mô hình cơ giới hóa trên rau', N'Để chuyển giao các kiến thức liên quan đến cơ giới hóa trên cây rau theo định hướng phát triển chuyển đổi cơ cấu kinh nông nghiệp đô thị, giúp nông dân tăng thu nhập, ổn định kinh tế, Trạm Khuyến nông huyện Củ Chi trực thuộc Trung tâm Khuyến nông thành phố đã triển khai mô hình trình diễn cơ giới hóa máy phun thuốc trong trồng rau.', N'2015-11-28 15:50:00', N'/Detail/detail_2', 1)
INSERT INTO [dbo].[ShowHome] ([Id], [linkImage], [Title], [Summary], [dateWritten], [linkPage], [Type]) VALUES (3, N'/Assets/HomePage/images/kn3.jpg', N'Hiệu quả mô hình cơ giới hóa nông nghiệp', N'Khuyến nông là một trong những ngành luôn sâu sát với bà con nông dân trên từng cánh đồng, từng trang trại. Cụ thể như Trạm Khuyến nông huyện Bình Chánh trực thuộc Trung Tâm Khuyến nông thành phố đã giúp nông dân ở địa phương có nhiều hiểu biết về khoa học kỹ thuật, cung cấp cây,', N'2015-11-28 15:45:00', N'/Detail/Detail_3', 1)
INSERT INTO [dbo].[ShowHome] ([Id], [linkImage], [Title], [Summary], [dateWritten], [linkPage], [Type]) VALUES (4, N'/Assets/HomePage/images/kn4.jpg', N'Hiệu quả áp dụng chuỗi liên kết sản xuất', N'Trong khi nhiều hộ nuôi cá tra thua lỗ phải treo ao, ngừng nuôi thì gia đình ông Nguyễn Văn Phú ở ấp Hòa Khánh, xã Vĩnh Thới, huyện Lai Vung, tỉnh Đồng Tháp vẫn “sống khỏe” với mô hình nuôi cá tra theo chuỗi liên kết sản xuất tiêu thụ.', N'2015-11-28 15:45:00', N'/Detail/Detail_4', 1)
INSERT INTO [dbo].[ShowHome] ([Id], [linkImage], [Title], [Summary], [dateWritten], [linkPage], [Type]) VALUES (5, N'/Assets/HomePage/images/kn6.jpg', N'Tỷ phú nông dân với thương hiệu ''Chanh không hạt Vica''', N'Bằng sự tiên phong, năng động trong việc trồng và xuất khẩu chanh không hạt Vica, mỗi năm bà Bùi Thị Ba thu lợi hàng tỷ đồng.', N'2015-11-28 15:39:00', N'/Detail/Detail_6', 2)
INSERT INTO [dbo].[ShowHome] ([Id], [linkImage], [Title], [Summary], [dateWritten], [linkPage], [Type]) VALUES (6, N'/Assets/HomePage/images/kn7.jpg', N'Nghệ núi Cấm: Trồng chơi kiếm cả chục triệu đồng', N'Trồng xen canh dưới tán cây vườn, không cần chăm sóc, bón phân nhưng chỉ sau vài tháng, người dân núi Cấm kiếm được cả chục triệu đồng.', N'2015-11-28 15:35:00', N'/Detail/Detail_7', 1)
INSERT INTO [dbo].[ShowHome] ([Id], [linkImage], [Title], [Summary], [dateWritten], [linkPage], [Type]) VALUES (7, N'/Assets/HomePage/images/kn9.jpg', N'Trồng cỏ nuôi bò xen trong vườn dừa hiệu quả kinh tế cao', N'Hiện nay toàn xã Phú Long huyện Bình Đại có trên 800 ha dừa, đây là một trong những xã có diện tích dừa lớn nhất của huyện. Tuy nhiên thời gian gần đây do dừa trái rớt giá nên thu nhập từ vườn dừa không cao, trong khi đa phần người trồng dừa ở Phú Long đang gặp nhiều khó khăn', N'2015-11-28 15:33:00', N'/Detail/Detail_8', 1)
