//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhuyenNong.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowHome
    {
        public int Id { get; set; }
        public string linkImage { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> dateWritten { get; set; }
        public string linkPage { get; set; }
        public int Type { get; set; }
    }
}
